### ISSUE TITLE
Error in line: C_twin_e = X_in_e + model.predict(X_in_e).reshape(-1)

### ISSUE THREAD

**Issue by Sapna091198** [Javihaus/Digital-Twin-in-python#1]
![Screenshot 2023-06-07 164607](https://github.com/Javihaus/Digital-Twin-in-python/assets/135851925/58ec2923-e272-43ca-8588-ed25c4fd0460)
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_336/336901451.py in <module>
      5 L_e = 1-e**(-K*cycles*temperature/time)
      6 X_in_e = -(L_e*dfb['Capacity'].iloc[0:1].values[0]) + dfb['Capacity'].iloc[0:1].values[0]
----> 7 C_twin_e = X_in_e + model.predict(X_in_e).reshape(-1)

C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py in error_handler(*args, **kwargs)
     68             # To get the full stack trace, call:
     69             # `tf.debugging.disable_traceback_filtering()`
---> 70             raise e.with_traceback(filtered_tb) from None
     71         finally:
     72             del filtered_tb

C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py in tf__predict_function(iterator)
     13                 try:
     14                     do_return = True
---> 15                     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16                 except:
     17                     do_return = False

ValueError: in user code:

    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 2111, in predict_step
        return self(x, training=False)
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None

    ValueError: Exception encountered when calling layer 'sequential' (type Sequential).
    
    Cannot iterate over a shape with unknown rank.
    
    Call arguments received by layer 'sequential' (type Sequential):
      • inputs=tf.Tensor(shape=<unknown>, dtype=float32)
      • training=False
      • mask=None

**Comment by ecubed108** [comment]
X_in_e =(-(L_e*dfb['Capacity'].iloc[0:1].values[0]) + dfb['Capacity'].iloc[0:1].values[0])

X_in_e=pd.Series(X_in_e)   # model.predict(  requires series data)

**Comment by groundlens-dev** [comment]
Thanks for the report, and sorry for the long delay.

Root cause: the model is trained on a pandas Series (X_in = dfb['C. Capacity']), which Keras silently expands to shape (n, 1). At extrapolation time X_in_e is a plain 1-D numpy array of shape (n,), which is not expanded — so Dense rejects it with expected min_ndim=2, found ndim=1.

@ecubed108's pd.Series workaround is correct and works for the same reason. The explicit fix:

```python
C_twin_e = X_in_e + model.predict(X_in_e.reshape(-1, 1)).ravel()
````

Use .ravel() on the output rather than leaving it 2-D — otherwise (n,) + (n,1) broadcasts to an (n, n) matrix without raising.

Fixed in the notebook, along with the fit/predict calls that were relying on the same implicit conversion. Note this notebook is the preserved v1 tutorial; current development is the v2 API under src/otwin/.
